version: 0.1
phases:
  build:
    commands:
      - dotnet restore ContinuousTraining
      - dotnet publish -c release ContinuousTraining
  post_build:
    commands:
      - dotnet ContinuousTraining/bin/release/netcoreapp2.0/publish/ContinuousTraining.dll ContinuousTraining/bin/release
artifacts:
  files:
    - ContinuousTraining/bin/release/netcoreapp2.0/publish/**/*
  discard-paths: yes